### ISSUE TITLE
icon images are missing in the "doc" folder.

### ISSUE THREAD

**Issue by nishaaanth2** [skgrush/CavernSeer#35]
Users/macbook/Library/Developer/Xcode/DerivedData/CavernSeer-gawkfmwkdwcclhbcxkuefzuazntc/Build
![Screenshot 2021-10-27 at 1 06 20 PM](https://user-images.githubusercontent.com/42349645/139020966-1f560428-0cf8-4716-9a9f-67362c84c445.png)
/Products/Debug-iphoneos/CavernSeer.app/icon-80.png

icon images are missing in the "doc" folder.

**Comment by skgrush** [comment]
Fixed in commit 61914b3.
That was weird, apparently files/folders called "icon" are by default gitignored? It was in my `~/.gitignore` file.
